const INITIAL_USER_INFORMATION = "INITIAL_USER_INFORMATION";
const SAVE_TOKEN = "SAVE_TOKEN";
const CLEAN_USER = "CLEAN_USER";
const INITIAL_COLLECT = "INITIAL_COLLECT";
const REMOVE_COLLECT = "REMOVE_COLLECT";
export { SAVE_TOKEN, INITIAL_USER_INFORMATION, INITIAL_COLLECT, REMOVE_COLLECT, CLEAN_USER };
